enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
start-at-login = true

[gaps]
inner.horizontal = [{monitor."built-in" = 10}, {monitor."dell" = 25}, 10]
inner.vertical = [{monitor."built-in" = 10}, {monitor."dell" = 25}, 10]
outer.left = [{monitor."built-in" = 10}, {monitor."dell" = 20}, 10]
outer.bottom = [{monitor."built-in" = 10}, {monitor."dell" = 100}, 10]
outer.top = [{monitor."built-in" = 10}, {monitor."dell" = 100}, 10]
outer.right = [{monitor."built-in" = 10}, {monitor."dell" = 20}, 10]

[mode.main.binding]
alt-enter = 'exec-and-forget open /Applications/WezTerm.app'
alt-shift-m = 'exec-and-forget open /Applications/Firefox.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-y = 'fullscreen'

alt-q = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'

cmd-shift-n = 'move-workspace-to-monitor next'
cmd-shift-p = 'move-workspace-to-monitor prev'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'secondary'
4 = 'secondary'
