# Theme: iceclimber
# URL: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/iceclimber.toml

[manager]
cwd = { fg = "#86a3f0" }

hovered         = { fg = "#559ba3", bg = "#1d1d22" }
preview_hovered = { fg = "#559ba3", bg = "#1d1d22" }

find_keyword  = { fg = "#abbceb", italic = true }
find_position = { fg = "#abbceb", bg = "reset", italic = true }

marker_copied   = { fg = "#7da77e" }
marker_cut      = { fg = "#e67e80" }
marker_selected = { fg = "#abbceb" }

tab_active   = { fg = "#e89bce", bg = "#2a2a31" }
tab_inactive = { fg = "#555568", bg = "#2a2a31" }
tab_width    = 1

count_cut      = { fg = "#abbceb", bg = "#1d1d22" }
count_copied   = { fg = "#abbceb", bg = "#1d1d22" }
count_selected = { fg = "#abbceb", bg = "#1d1d22" }

border_symbol = "│"
border_style  = { fg = "#555568" }

[mode]
normal_main = { fg = "#171719", bg = "#86a3f0", bold = true }
normal_alt = { fg = "#171719", bg = "#86a3f0", bold = true }
select_main = { fg = "#171719", bg = "#8a88db", bold = true }
select_alt = { fg = "#171719", bg = "#8a88db", bold = true }
unset_main  = { fg = "#171719", bg = "#559ba3", bold = true }
unset_alt  = { fg = "#171719", bg = "#559ba3", bold = true }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#2a2a31", bg = "#2a2a31" }

progress_label  = { fg = "#abbceb", bold = true }
progress_normal = { fg = "#abbceb", bg = "#2a2a31" }
progress_error  = { fg = "#171719", bg = "#e67e80" }

permissions_t = { fg = "#bbbac1" }
permissions_r = { fg = "#dbbc8a" }
permissions_w = { fg = "#e67e80" }
permissions_x = { fg = "#86a3f0" }
permissions_s = { fg = "#9b99a3" }

[input]
border   = { fg = "#555568" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#555568" }
active   = { fg = "#8a88db" }
inactive = {}

[tasks]
border  = { fg = "#555568" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#151517" }
cand            = { fg = "#559ba3" }
rest            = { fg = "#e3a462" }
desc            = { fg = "#7da77e" }
separator       = "  "
separator_style = { fg = "#9b99a3"}

[help]
on      = { fg = "#e3a462" }
run    = { fg = "#7da77e" }
desc    = { fg = "#555568" }
hovered = { fg = "#559ba3", bg = "#1d1d22", bold = true }
footer  = { fg = "#555568", bg = "#1d1d22" }

[filetype]
rules = [
# Media
{ mime = "image/*", fg = "#e89bce"},
{ mime = "{audio,video}/*", fg = "#7da77e"},

# Archives
{ mime = "application/{,g}zip", fg = "#e67e80"},
{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80"},

# Fallback
{ name = "*", fg = "#bbbac1"},
{ name = "*/", fg = "#86a3f0"}
]

