# Theme: coffeecat
# URL: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/coffeecat.toml

[manager]
cwd = { fg = "#a2bafa" }

hovered         = { fg = "#ebabd5", bg = "#262524" }
preview_hovered = { fg = "#ebabd5", bg = "#262524" }

find_keyword  = { fg = "#cfa991", italic = true }
find_position = { fg = "#cfa991", bg = "reset", italic = true }

marker_copied   = { fg = "#8ab56d" }
marker_cut      = { fg = "#d47b7d" }
marker_selected = { fg = "#cfa991" }

tab_active   = { fg = "#d67287", bg = "#383737" }
tab_inactive = { fg = "#6a6a6a", bg = "#383737" }
tab_width    = 1

count_cut      = { fg = "#cfa991", bg = "#262524" }
count_copied   = { fg = "#cfa991", bg = "#262524" }
count_selected = { fg = "#cfa991", bg = "#262524" }

border_symbol = "│"
border_style  = { fg = "#6a6a6a" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#383737", bg = "#383737" }

mode_normal = { fg = "#1e1d1c", bg = "#a2bafa", bold = true }
mode_select = { fg = "#1e1d1c", bg = "#cfa991", bold = true }
mode_unset  = { fg = "#1e1d1c", bg = "#78bfc4", bold = true }

progress_label  = { fg = "#cfa991", bold = true }
progress_normal = { fg = "#cfa991", bg = "#383737" }
progress_error  = { fg = "#1e1d1c", bg = "#d47b7d" }

permissions_t = { fg = "#bbbac1" }
permissions_r = { fg = "#ebc686" }
permissions_w = { fg = "#d67287" }
permissions_x = { fg = "#a2bafa" }
permissions_s = { fg = "#9b99a3" }

[input]
border   = { fg = "#6a6a6a" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#6a6a6a" }
active   = { fg = "#e8a85f" }
inactive = {}

[tasks]
border  = { fg = "#6a6a6a" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#1B1A19" }
cand            = { fg = "#ebabd5" }
rest            = { fg = "#78bfc4" }
desc            = { fg = "#8ab56d" }
separator       = "  "
separator_style = { fg = "#9b99a3"}

[help]
on      = { fg = "#78bfc4" }
run    = { fg = "#8ab56d" }
desc    = { fg = "#6a6a6a" }
hovered = { fg = "#ebabd5", bg = "#262524", bold = true }
footer  = { fg = "#6a6a6a", bg = "#262524" }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "#ebabd5"},
  { mime = "{audio,video}/*", fg = "#8ab56d"},

  # Archives
  { mime = "application/{,g}zip", fg = "#d67287"},
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d67287"},

  # Fallback
  { name = "*", fg = "#bbbac1"},
  { name = "*/", fg = "#a2bafa"}
]

