#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config layout bsp                    # let yabai manage layout
yabai -m config mouse_follows_focus on        # move mouse to focused display
yabai -m config focus_follows_mouse off       # focus window under mouse
yabai -m config window_placement second_child # add new windows to right or bottom
yabai -m config auto_balance on               # auto split ratios
yabai -m config split_ratio 0.50              # if auto balance is off -> split windows 50:50
yabai -m config window_shadow off             # remove macos window shadow
yabai -m config window_animation_duration 0.0 # no window animation
yabai -m config window_opacity_duration 0.0   # no window opacity animation
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

yabai -m config bottom_padding 25
yabai -m config top_padding 25
yabai -m config left_padding 25
yabai -m config right_padding 25
yabai -m config window_gap 10

# scripts for changing padding settings on external monitor
yabai -m signal --add event=display_added action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=display_removed action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=display_changed action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=space_created action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=window_created action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=window_destroyed action="~/.config/scripts/desktop_padding.sh"

yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^(Finder|About This Mac|System Settings)$" manage=off
yabai -m rule --add app="^Anki$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^$" manage=off
