#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config window_border on
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist off
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_frame_rate 120
yabai -m config window_opacity_duration 0.0
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.80
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config active_window_border_color 0xffffffff
yabai -m config normal_window_border_color 0xff5555ff
yabai -m config window_border_width 2
yabai -m config window_border_radius 11
yabai -m config window_border_blur off
yabai -m config window_border_hidpi on
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance on

yabai -m config bottom_padding 25
yabai -m config top_padding 25
yabai -m config left_padding 25
yabai -m config right_padding 25
yabai -m config window_gap 10

yabai -m signal --add event=display_added action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=display_removed action="~/.config/scripts/desktop_padding.sh"
yabai -m signal --add event=space_created action="~/.config/scripts/desktop_padding.sh"

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

yabai -m rule --add app="^(Finder|About This Mac|System Settings)$" manage=off
yabai -m rule --add app="^Anki$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Messages$" manage=off

yabai -m config layout bsp
