$c_fg             = rgb(dddddd)

$c_black          = rgb(191919)
$c_red            = rgb(896956)
$c_green          = rgb(5f645f)
$c_yellow         = rgb(918f84)
$c_blue           = rgb(6a6a7a)
$c_magenta        = rgb(676068)
$c_cyan           = rgb(575d70)
$c_white          = rgb(616167)

$c_bright_black   = rgb(2a2927)
$c_bright_red     = rgb(ab836c)
$c_bright_green   = rgb(717d6e)
$c_bright_yellow  = rgb(b5b3a5)
$c_bright_blue    = rgb(858599)
$c_bright_magenta = rgb(817882)
$c_bright_cyan    = rgb(6d748c)
$c_bright_white   = rgb(aea09f)
