[colors]
foreground = "#adacac"
background = "#161616"
# background = "#111111" # alternate, darker bg
cursor_bg = "#adacac"
cursor_border = "#696969"
cursor_fg = "#161616"
selection_bg = "#333333"
selection_fg = "#8a879c"
split = "#696969"
compose_cursor = "#a7ab93"
scrollbar_thumb = "#1b1c1d"

ansi = ["#696969", "#9e5560", "#5C635F", "#b0b58a", "#565A63", "#5C5A66", "#695C55", "#717070"]
brights = ["#696969", "#9c797d", "#8a968f", "#b5ae84", "#808796", "#8a879c", "#a18b7f", "#adacac"]

[colors.tab_bar]
inactive_tab_edge = "#717070"
background = "#161616"

[colors.tab_bar.active_tab]
fg_color = "#a7ab93"
bg_color = "#333333"

[colors.tab_bar.inactive_tab]
fg_color = "#696969"
bg_color = "#1b1c1d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#696969"
bg_color = "#1b1c1d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a7ab93"
bg_color = "#333333"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a7ab93"
bg_color = "#161616"

[metadata]
aliases = []
name = "hojicha"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/wezterm/hojicha.toml"
author = "Casey Miller"
