[colors]
foreground = "#adadcc"
background = "#121315"
# background = "#111111" # alternate, darker bg
cursor_bg = "#adadcc"
cursor_border = "#666a82"
cursor_fg = "#121315"
selection_bg = "#262830"
selection_fg = "#9bbdb8"
split = "#666a82"
compose_cursor = "#a8a6f5"
scrollbar_thumb = "#16171b"

ansi = ["#666a82", "#ba5f60", "#647977", "#c4959c", "#6172A0", "#6C6B9B", "#436285", "#6F6F83"]
brights = ["#666a82", "#ad82a2", "#9bbdb8", "#d2af98", "#95b1fc", "#a8a6f5", "#6397cf", "#adadcc"]

[colors.tab_bar]
inactive_tab_edge = "#6F6F83"
background = "#121315"

[colors.tab_bar.active_tab]
fg_color = "#a8a6f5"
bg_color = "#262830"

[colors.tab_bar.inactive_tab]
fg_color = "#666a82"
bg_color = "#16171b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#666a82"
bg_color = "#16171b"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a8a6f5"
bg_color = "#262830"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a8a6f5"
bg_color = "#121315"

[metadata]
aliases = []
name = "roseprime"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/wezterm/roseprime.toml"
author = "Casey Miller"
