# name: ICECLIMBER colors for Yazi
# url: https://github.com/sxyazi/yazi
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/yazi/iceclimber.toml
# author: Casey Miller

[mgr]
cwd = { fg = "#cc93b8" }

hovered = { fg = "#a8a6de", bg = "#1d1d22" }
preview_hovered = { fg = "#a8a6de", bg = "#1d1d22" }

find_keyword = { fg = "#629da3", italic = true }
find_position = { fg = "#629da3", bg = "reset", italic = true }

marker_copied = { fg = "#cfa18c", bg = "#cfa18c" }
marker_cut = { fg = "#e67e80", bg = "#e67e80", crossed = true }
marker_marked = { bg = "#abbceb", blink = true }
marker_selected = { bg = "#abbceb", blink = true }

tab_active = { fg = "#86a3f0", bg = "#1d1d22", bold = true, reversed = true }
tab_inactive = { fg = "#555568", bg = "#1d1d22" }
tab_width = 1

count_cut = { fg = "#e67e80" }
count_copied = { fg = "#cfa18c" }
count_selected = { fg = "#abbceb", italic = true, blink = true }

border_symbol = "│"
border_style = { fg = "#555568" }

[mode]
normal_main = { fg = "#171719", bg = "#8a88db" }
normal_alt = { fg = "#171719", bg = "#8a88db" }
select_main = { fg = "#171719", bg = "#abbceb" }
select_alt = { fg = "#171719", bg = "#abbceb" }
unset_main = { fg = "#171719", bg = "#629da3" }
unset_alt = { fg = "#171719", bg = "#629da3" }

[status]
overall = { fg = "#555568", bg = "#171719", bold = true }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#86a3f0", bg = "#2a2a31" }
progress_normal = { fg = "#86a3f0", bg = "#2a2a31" }
progress_error = { fg = "#e67e80", bg = "#2a2a31" }

permissions_t = { fg = "#a8a6de" }
permissions_r = { fg = "#629da3" }
permissions_w = { fg = "#8a88db" }
permissions_x = { fg = "#cc93b8" }
permissions_s = { fg = "#86a3f0" }

[input]
border = { fg = "#555568" }
title = { fg = "#86a3f0" }
value = {}
selected = { fg = "#bbbac1", bg = "#2a2a31" }

[confirm]
border = { fg = "#555568" }
title = { fg = "#86a3f0" }
btn_yes = { fg = "#e67e80", bg = "#1d1d22" }
btn_no = { fg = "#658c6d", bg = "#1d1d22" }

[tasks]
border = { fg = "#555568" }
title = { fg = "#86a3f0" }
hovered = { underline = true }

[which]
mask = { bg = "#151517" }
cand = { fg = "#cfa18c" }
rest = { fg = "#a8a6de" }
desc = { fg = "#629da3" }
separator = "  "
separator_style = { fg = "#9b99a3" }

[spot]
border = { fg = "#555568" }
title = { fg = "#86a3f0" }
tbl_col = { fg = "#629da3" }
tbl_cell = { fg = "#a8a6de", bg = "#1d1d22" }

[help]
on = { fg = "#cfa18c" }
run = { fg = "#629da3" }
desc = { fg = "#555568" }
hovered = { bg = "#1d1d22", bold = true }
footer = { fg = "#8a88db", bg = "#1d1d22" }

[notify]
title_info = { fg = "#86a3f0" }
title_warn = { fg = "#ad9368" }
title_error = { fg = "#e67e80" }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "#86a3f0" },
  { mime = "{audio,video}/*", fg = "#86a3f0" },

  # Archives
  { mime = "application/{,g}zip", fg = "#9b99a3" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#9b99a3" },

  # Fallback
  { name = "*", fg = "#bbbac1" },
  { name = "*/", fg = "#6b6b99" },
]
