[mgr]
show_hidden = true

[preview]
tab_size = 2

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
]
pdf = [
  { run = 'zathura "$@"', desc = "Open with zathura" },
]

[open]
rules = [
  { name = "*/", use = [ "edit", "open" ] },
  { mime = "text/*", use = [ "edit" ] },
  { mime = "application/pdf", use = [ "pdf" ] },
  { name = "*", use = [ "open" ] },
]
