return {
  { "stevearc/dressing.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "jesseduffield/lazygit", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "echasnovski/mini.animate", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
}
