[mode]
normal_main = { fg = "black", bg = "lightblue" }
normal_alt = { fg = "black", bg = "blue" }
select_main = { fg = "black", bg = "lightyellow" }
select_alt = { fg = "black", bg = "yellow" }
unset_main = { fg = "black", bg = "lightcyan" }
unset_alt = { fg = "black", bg = "cyan" }

[tabs]
active = { fg = "black", bg = "green" }
inactive = { fg = "green", bg = "black" }

[indicator]
current = { fg = "lightgreen", bg = "black" }
parent = { fg = "gray", bg = "black" }
preview = { fg = "gray", bg = "black" }
